//! The XDG desktop entry, generated rather than hand-maintained.
//!
//! `packaging/scurry-tray.desktop` is the committed output of [`desktop_entry`]
//! and a test keeps the two in step, so the packaged file cannot quietly drift
//! from what the binary claims about itself.

pub fn desktop_entry() -> String {
    format!(
        "# Generated by `scurry-tray --print-desktop-entry`.\n\
         # Regenerate rather than editing this file by hand.\n\
         [Desktop Entry]\n\
         Type=Application\n\
         Name=scurry\n\
         Comment={comment}\n\
         Keywords=mouse;keyboard;kvm;bluetooth;input;\n\
         Exec=scurry-tray\n\
         Icon=scurry\n\
         Categories=Utility;System;\n\
         StartupNotify=false\n\
         X-GNOME-Autostart-enabled=true\n",
        comment = "Share one mouse and keyboard across machines",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    const COMMITTED: &str = include_str!("../../../packaging/scurry-tray.desktop");

    /// When this fails, run:
    ///   cargo run -p scurry-tray -- --print-desktop-entry > packaging/scurry-tray.desktop
    #[test]
    fn committed_desktop_entry_is_current() {
        assert_eq!(desktop_entry(), COMMITTED, "packaging/scurry-tray.desktop is stale");
    }

    #[test]
    fn desktop_entry_has_the_keys_launchers_need() {
        let entry = desktop_entry();
        for key in ["Type=", "Name=", "Exec=", "Icon=", "Categories="] {
            assert!(entry.contains(key), "desktop entry is missing {key}");
        }
    }
}
